name: nllb
channels:
- conda-forge
- defaults
- pytorch
dependencies:
- python=3.9.*
- pip
- numpy=1.*.*
- pytorch=1.9.*
- tqdm
- pip:
  - more_itertools
  - transformers
  - pandas
  - scikit-learn
  - nltk
  - matplotlib
